"use client";

import { useState } from "react";
import { QrCode, X, Download, ExternalLink } from "lucide-react";

interface LinkQRCodeProps {
    slug: string;
    linkName: string;
}

export function LinkQRCode({ slug, linkName }: LinkQRCodeProps) {
    const [isOpen, setIsOpen] = useState(false);
    const [isDownloading, setIsDownloading] = useState(false);

    // Construct the public URL for the short link
    // We try to get the base URL from window.location if possible, or fallback to placeholder
    const baseUrl = typeof window !== "undefined" ? window.location.origin : "";
    const publicUrl = `${baseUrl}/${slug}`;
    const qrCodeUrl = `https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=${encodeURIComponent(publicUrl)}`;

    const handleDownload = async () => {
        setIsDownloading(true);
        try {
            const response = await fetch(qrCodeUrl);
            const blob = await response.blob();
            const url = window.URL.createObjectURL(blob);
            const link = document.createElement("a");
            link.href = url;
            link.download = `qr-code-${slug}.png`;
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);
            window.URL.revokeObjectURL(url);
        } catch (error) {
            console.error("Failed to download QR code:", error);
        } finally {
            setIsDownloading(false);
        }
    };

    return (
        <>
            <button
                onClick={() => setIsOpen(true)}
                className="p-2.5 rounded-xl border border-gray-200 text-gray-600 hover:bg-indigo-50 hover:border-indigo-200 hover:text-indigo-600 transition-colors bg-white shadow-sm flex items-center justify-center"
                title="View QR Code"
            >
                <QrCode className="w-4 h-4" />
            </button>

            {isOpen && (
                <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm animate-in fade-in duration-200">
                    <div className="bg-white rounded-3xl shadow-2xl max-w-sm w-full overflow-hidden animate-in zoom-in-95 duration-200">
                        {/* Modal Header */}
                        <div className="p-6 border-b border-gray-50 flex items-center justify-between bg-gray-50/50">
                            <div>
                                <h3 className="font-bold text-gray-900 text-lg">QR Code</h3>
                                <p className="text-xs text-gray-500 font-medium truncate max-w-[200px]">{linkName}</p>
                            </div>
                            <button
                                onClick={() => setIsOpen(false)}
                                className="p-2 hover:bg-gray-200 rounded-full transition-colors"
                            >
                                <X className="w-5 h-5 text-gray-500" />
                            </button>
                        </div>

                        {/* Modal Body */}
                        <div className="p-8 flex flex-col items-center">
                            <div className="p-4 bg-white rounded-2xl border-2 border-dashed border-gray-100 mb-6 shadow-inner">
                                <img
                                    src={qrCodeUrl}
                                    alt={`QR Code for ${slug}`}
                                    className="w-48 h-48 block rounded-lg"
                                />
                            </div>

                            <p className="text-sm font-mono text-gray-400 bg-gray-50 px-3 py-1.5 rounded-lg border border-gray-100 mb-6 flex items-center gap-2">
                                <ExternalLink className="w-3 h-3" /> /{slug}
                            </p>

                            <button
                                onClick={handleDownload}
                                disabled={isDownloading}
                                className="w-full bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-3.5 rounded-2xl flex items-center justify-center gap-2 transition-all active:scale-[0.98] shadow-lg shadow-indigo-100 disabled:opacity-50"
                            >
                                <Download className={`w-5 h-5 ${isDownloading ? 'animate-bounce' : ''}`} />
                                {isDownloading ? "Downloading..." : "Download PNG"}
                            </button>
                        </div>

                        {/* Modal Footer */}
                        <div className="px-8 pb-6 text-center">
                            <p className="text-[10px] text-gray-400 uppercase tracking-widest font-bold">
                                Generated by Lnk-Tree
                            </p>
                        </div>
                    </div>
                </div>
            )}
        </>
    );
}
